import { Header } from "./components/header";
import { Footer } from "./components/footer";
import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`mx-auto max-w-[1840px] antialiased`}>
				<Header />
				<main className="bg-[#16384E]">{children}</main>
				<Footer />
			</body>
		</html>
	);
}
